"""empty message

Revision ID: c64b3ecbdecb
Revises: 2c9d25b0315a
Create Date: 2025-02-12 11:43:15.864027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c64b3ecbdecb'
down_revision = '2c9d25b0315a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_category_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_category_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('sub_category_table_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'category_table', ['subcategory_category_id'], ['category_id'], ondelete='CASCADE')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_category_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sub_category_table_ibfk_1', 'category_table', ['category_id'], ['category_id'], ondelete='CASCADE')
        batch_op.drop_column('subcategory_category_id')

    # ### end Alembic commands ###
