"""Initial migration

Revision ID: ea5283e09d12
Revises: 
Create Date: 2025-02-28 11:22:33.250180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea5283e09d12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('modify_at', sa.Integer(), nullable=True))
        batch_op.alter_column('login_password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=16),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_table', schema=None) as batch_op:
        batch_op.alter_column('login_password',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=16),
               existing_nullable=False)
        batch_op.drop_column('modify_at')
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
