import jwt

token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczOTk0NDU0NSwianRpIjoiMjFkZDNkOGYtNTVlMi00NDQwLWFhZGYtYWNkYzZmNjAyOTljIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJsb2dpbl9pZCI6MTcsImxvZ2luX3VzZXJuYW1lIjoibmloYXIiLCJsb2dpbl9wYXNzd29yZCI6IlNhYmhhZGl5YUAxMjMifSwibmJmIjoxNzM5OTQ0NTQ1LCJleHAiOjE3Mzk5NDU0NDV9.MCDlOvCPjbsGwieCcIx3fuZ8S3FukY8-o6z2M_oRzR4"
decoded = jwt.decode(token, options={"verify_signature": False})
print(decoded)